# Generated by Django 4.1.3 on 2022-11-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('projects', '0007_remove_project_lead_project_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lead',
        ),
        migrations.AddField(
            model_name='project',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
            preserve_default=False,
        ),
    ]
