# Generated by Django 4.1.3 on 2022-11-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
