# Generated by Django 4.1.1 on 2022-11-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_report_timeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeslot',
        ),
    ]
