# Generated by Django 4.1.1 on 2022-11-27 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0009_alter_project_project_name'),
        ('members', '0001_initial'),
        ('clients', '0004_alter_client_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('time', models.DecimalField(decimal_places=1, max_digits=3)),
                ('overtime', models.DecimalField(decimal_places=1, max_digits=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
