# Generated by Django 4.1.3 on 2022-11-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('hours_per_week', models.DecimalField(decimal_places=1, max_digits=4)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30)),
                ('role', models.CharField(choices=[('Worker', 'Worker'), ('Admin', 'Admin')], default='Worker', max_length=30)),
            ],
        ),
    ]
